project './Note.xcodeproj/'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Note' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Note

  target 'NoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NoteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
